name: Docker Build CI
env:
  IMAGE_TAG: '1.0'
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
          include-prerelease: false
      - name: Run tests
        run: |
          dotnet test
      - name: Docker build
        run: |
          docker build . -f MinApi/Dockerfile -t edgarknapp/minapi:${{ env.IMAGE_TAG }}.${{ env.GITHUB_RUN_NUMBER }}
      - name: DockerHub login
        env: 
          DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: |
          docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASSWORD
      - name: Docker push
        run: |
          docker push edgarknapp/minapi:${{ env.IMAGE_TAG }}.${{ env.GITHUB_RUN_NUMBER }}
