name: Docker Build CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: DockerHub login
        env: 
          DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
          OCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: |
          docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASSWORD
      - name: Docker build
        run: |
          docker build ./MinApi -t edgarknapp/minapi:1.0.0
  
