name: Docker Build CI
env:
  IMAGE_TAG: 1.0.$GITHUB_RUN_NUMBER
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x'
          include-prerelease: false
      - name: Run tests
        run: |
          dotnet test
      - name: Docker build
        run: |
          docker build . -f MinApi/Dockerfile -t edgarknapp/minapi:${{ env.IMAGE_TAG }}
      - name: Docker Login
        uses: docker/login-action@v2.0.0
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Docker push
        run: |
          docker push edgarknapp/minapi:${{ env.IMAGE_TAG }}
