name: Docker Build CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
          include-prerelease: true
      - name: Run tests
        run: |
          dotnet test
      - name: Docker build
        run: |
          docker build . -f MinApi/Dockerfile -t edgarknapp/minapi:1.0.0
      - name: DockerHub login
        env: 
          DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: |
          docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASSWORD
      - name: Docker push
        run: |
          docker push edgarknapp/minapi:1.0.0
